---
  - name: check role inputs are valid
    block:
      - name: check nutanix_prism_eula_host
        ansible.builtin.fail:
          msg: "the variable 'nutanix_prism_eula_host' has to be provided."
        when:
          - nutanix_prism_eula_host is not defined or nutanix_prism_eula_host == ""

      - name: check nutanix_prism_eula_password
        ansible.builtin.fail:
          msg: "the variable 'nutanix_prism_eula_password' has to be provided."
        when:
          - nutanix_prism_eula_password is not defined or nutanix_prism_eula_password == ""

      - ansible.builtin.fail:
          msg: "the variables 'nutanix_prism_eula_full_name', 'nutanix_prism_eula_company_name' and 'nutanix_prism_eula_job_title' must be provided to accept the Nutanix EULA."
        when:
          - nutanix_prism_eula_full_name is not defined or nutanix_prism_eula_full_name == ""
          - nutanix_prism_eula_company_name is not defined or nutanix_prism_eula_company_name == ""
          - nutanix_prism_eula_job_title is not defined or nutanix_prism_eula_job_title == ""
